#created on: 11/04/2009
package com.fiuba.fallas;

#list any import classes here.

/** R01
* Si la disponibilidad es menor a 5 y la velocidad menor a 3, descarto la posibilidad de utilizar la máquina.
*/
rule "Maquina descartada, no economizo seguro."
	salience 200
	when
		$maquina : Maquina ($disponibilidad : disponibilidad < 0.5, $id : id)
		$pp : Maquina ($velocidad : velocidad < 3, $id : id)s
	then 
		System.out.println("La relación de disponibilidad y tiempo de impresión de la máquina " + $maquina.getNombre() + " la hacen inapropiada.");
		$maquina.setAnulada(true);
		update($maquina);		
end

/** R02 
* Si la maquina tiene disponibilidad igual a 0 la descarto para el trabajo.
*/
rule "Maquina no disponible"
	salience 200
	when
		$maquina : Maquina ($disponibilidad : disponibilidad == 0.0, $id : id)
	then 
		System.out.println("La máquina " + $maquina.getNombre() + " no está disponible.");
		$maquina.setAnulada(true);
		update($maquina);		
end

/** R03 
* Si la maquina no tiene la cantidad de colores especificada en el trabajo la descarto
*/
rule "Colores insuficientes"
	salience 200
	when
		$maquina : Maquina ($id : id)
		$trabajo : Trabajo ($id : id)
	then 
		$maquina.setAnulada($trabajo.getColores()>$maquina.getColores());
		update($maquina);
end

/** R04
* Regla de calculo de tiempo de impresion
*/
rule "Tiempo de impresion"
	salience 20
	no-loop
	when
		$maquina : Maquina ($anulada : anulada == false, $id : id)
		$trabajo : Trabajo ($id : id)
	then
		$maquina.setTiempoDeImpresion(($maquina.getVelocidad()*$trabajo.getCantidadHojas())/($maquina.getDisponibilidad());
		System.out.println("La impresión con la máquina " + $maquina.getNombre() + " cuesta $" $maquina.getCosto());
end

/** R05
* Regla de calculo de precio por maquina.
*/
rule "Precio por maquina"
	salience 20
	no-loop
	when
		$maquina : Maquina ($anulada : anulada == false, $id : id)
		$trabajo : Trabajo ($id : id)
	then
		$maquina.setCosto(($maquina.getCostoPorHoja() * $trabajo.getCantidadHojas()) + (($maquina.getCostoPorHora())*($maquina.getTiempoDeImpresion());
		System.out.println("La impresión con la máquina " + $maquina.getNombre() + " cuesta $" $maquina.getCosto());
end


